### ISSUE TITLE
[SUGESTÃO] - Adicionar hooks pre-push

### ISSUE THREAD

**Issue by drianoaz** [geandre/vue-check#1]
## Descrição

Para evitar que outros desenvolvedores enviem pull requests com códigos fora do padrão, é considerado uma boa prática adicionarmos hooks para verificar o código fonte está dentro do style-guide do eslint. Para isso podemos adicionar o plugin husky no projeto.

[O husky nos auxilia a trabalhar com hooks do git, ajudando a evitar commits e pushs fora do padrão.](https://github.com/typicode/husky)

## Sugestão

Para não esquentarmos a cabeça com esse tipo de coisa, sugiro que:

- Adicionemos um hook pre-push para gerarmos a documentação novamente antes de enviarmos para o github.
- Adicionemos um hook pre-commit para garantir que o código digitado está dentro do padrão do eslint antes de fazermos qualquer commit.

**Comment by geandre** [comment]
Fixed #87261e7
